baseURL       = "https://mondaiycoffee.com/"
languageCode  = "en-us"
title         = "Mond(AI)y Coffee"
buildFuture   = true   # allows upcoming speaker posts to appear before their date

[markup.goldmark.renderer]
  unsafe = true
